version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: stations
        description: "Métadonnées stations (id, nom, lat, lon, altitude, date ouverture)"
        columns: 
          - name: "Id_station"
            tests: 
              - not_null
      - name: obs_hourly
        description: "Observations horaires Météo-France (24h glissantes)"
        loaded_at_field: load_time
        freshness:
          warn_after: {count: 2, period: hour}
          error_after: {count: 4, period: hour}
        columns:
          - name: geo_id_insee
            tests:
              - not_null
          - name: validity_time
            tests:
              - not_null
