name: 'weather_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'weather_dbt'

# These configurations specify where dbt should look for different types of files.
model-paths: ["weather_dbt/models"]
analysis-paths: ["weather_dbt/analyses"]
test-paths: ["weather_dbt/tests"]
seed-paths: ["weather_dbt/seeds"]
macro-paths: ["weather_dbt/macros"]
snapshot-paths: ["weather_dbt/snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

dbt-cloud:
    project-id: 70471823521229

models:
  weather_dbt:                   # dossier racine du projet (== name dans dbt_project.yml)
    +materialized: view          # défaut global
    staging:                     # -> dossier models/staging/
      +schema: staging
      meteofrance:               # -> dossier models/staging/meteofrance/
        +tags: ["stg","meteofrance"]

    intermediate:                # -> dossier models/intermediate/
      +schema: intermediate
      meteofrance:               # -> dossier models/intermediate/meteofrance/
        +tags: ["int","meteofrance"]

    marts:                       # -> dossier models/marts/
      +schema: marts  
      +materialized: table        # défaut pour les marts
      meteofrance:               # -> dossier models/marts/meteofrance/
        +tags: ["mart","meteofrance"]

seeds:
  +quote_columns: false
  +column_types:
    level: integer
    label: varchar
    ms_min: double
    ms_max: double
