name: 'dbt_weather'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_weather'

# These configurations specify where dbt should look for different types of files.
model-paths: ["dbt_weather/models"]
analysis-paths: ["dbt_weather/analyses"]
test-paths: ["dbt_weather/tests"]
seed-paths: ["dbt_weather/seeds"]
macro-paths: ["dbt_weather/macros"]
snapshot-paths: ["dbt_weather/snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbt_weather:
    staging:
      +materialized: view


dbt-cloud:
    project-id: 70471823521229