name: 'weather_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'weather_dbt'

# These configurations specify where dbt should look for different types of files.
model-paths: ["weather_dbt/models"]
analysis-paths: ["weather_dbt/analyses"]
test-paths: ["weather_dbt/tests"]
seed-paths: ["weather_dbt/seeds"]
macro-paths: ["weather_dbt/macros"]
snapshot-paths: ["weather_dbt/snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  weather_dbt:                   # dossier racine du projet (== name dans dbt_project.yml)
    +materialized: view          # défaut global
    staging:                     # -> dossier models/staging/
      +schema: staging
      +tags: ["stg"]

    intermediate:                # -> dossier models/intermediate/
      +schema: intermediate
      +tags: ["int"]

    marts:                       # -> dossier models/marts/
      +schema: marts  
      +materialized: table        # défaut pour les marts
      +tags: ["mart"]

