version: 2
models:
  - name: int_obs_enriched
    description: "Observations horaires enrichies des métadonnées station + clé événement."
    columns:
      - name: event_id
        description: "station_id + validity_time_utc"
        tests: [not_null, unique]
      - name: station_id
        description: "Identifiant station"
        tests: [not_null]
      - name: station_name
        description: "Nom station"
      - name: validity_time_utc
        description: "Horodatage UTC de la mesure"
        tests: [not_null]
      - name: temperature_c
        description: "Température °C"
      - name: humidity_pct
        description: "Humidité %"
      - name: precip_mm
        description: "Précipitations mm"
      - name: wind_speed_ms
        description: "Vent moyen m/s"
      - name: pressure_sea_pa
        description: "Pression mer Pa"
